#!/usr/bin/env python3

"""
Generate pip_dependency_database.py for the pyz app by aggregating JSON files
from installer/dep_database and embedding both the resulting DATA and the
project pyproject.toml into the output file as raw triple-quoted strings.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _read_dep_json(dep_dir: Path) -> dict:
    aggregated: dict[str, object] = {}
    for path in sorted(dep_dir.glob("*.json")):
        name = path.stem.lower()
        try:
            aggregated[name] = json.loads(path.read_text())
        except Exception as exc:  # pragma: no cover - build-time guard
            print(f"{name} had an error: {exc}", file=sys.stderr)
    return aggregated


def _escape_triple(s: str) -> str:
    # Escape triple quotes inside the string to keep the literal intact.
    return s.replace('"""', '\\"\\"\\"')


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    dep_dir = repo_root / "dep_database"
    out_path = repo_root / "pyz_app" / "support" / "pip_dependency_database.py"
    pyproject_path = repo_root.parent / "pyproject.toml"

    data = _read_dep_json(dep_dir)
    data_json = json.dumps(data, indent=2, sort_keys=True)
    escaped_data = _escape_triple(data_json)

    pyproject_text = pyproject_path.read_text()
    escaped_pyproject = _escape_triple(pyproject_text)

    out_path.write_text(
        (
            "#!/usr/bin/env python3\n"
            "# Auto-generated by build_pip_dependency_database.py -- DO NOT EDIT BY HAND\n"
            "import json\n\n"
            'RAW_DATA = r"""%s"""\n'
            'RAW_PROJECT_TOML = r"""%s"""\n\n'
            "DATA = json.loads(RAW_DATA)\n"
            "PROJECT_TOML = RAW_PROJECT_TOML\n\n"
            '__all__ = ["DATA", "PROJECT_TOML"]\n'
        )
        % (escaped_data, escaped_pyproject)
    )


if __name__ == "__main__":
    main()
